[package]
name = "orbit"
version = "0.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
tokio = { version = "1", features = ["full"] }
reqwest = "0.11"
zip = "0.6"
tempfile = "3.3"