[package]
name = "orbit"
version = "0.2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
# supportive installer program to package with the orbit distribution
name = "install"
path = "src/installer/main.rs"

[dependencies]
colored = "2"
tokio = { version = "1", features = ["full"] }
reqwest = "0.11"
zip = "0.6"
tempfile = "3.3"
home = "0.5"
toml_edit = "0.14"
git2 = "0.14"
glob = "0.3"
ignore = "0.4"
fs_extra = "1.2"