name: build
on:
  workflow_call:

env:
  PROJECT: orbit

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Fetch repository
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Configure Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Enable Cargo caching
        uses: Swatinem/rust-cache@v2

      - name: Identify target triple and current version
        shell: bash
        run: |
          echo "TARGET=$(cargo run --bin target-triple --quiet)" >> $GITHUB_ENV
          echo "VERSION=$(python ./tools/evalver.py --version)" >> $GITHUB_ENV

      - name: Update manual pages
        run: python ./tools/rsmangen.py

      - name: Build orbit binary
        run: cargo build --release --bin orbit

      - name: Test
        run: cargo test

      - name: Build installer binary
        run: cargo build --release --bin install

      - name: Package and compress binary executable
        run: python ./tools/pack.py ${{ env.VERSION }}-${{ env.TARGET }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PROJECT }}-${{ env.VERSION }}-${{ env.TARGET }}
          path: ./${{ env.PROJECT }}-${{ env.VERSION }}-${{ env.TARGET }}.zip