name: build
on:
  workflow_call:

env:
  PROJECT: orbit

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Fetch repository
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.x

      - name: Configure rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      # - name: Enable Cargo caching
        # uses: Swatinem/rust-cache@v1

      - name: Identify target triple and current version
        shell: bash
        run: |
          rustc ./tools/target-triple.rs -o ./tools/target-triple.exe
          echo "TARGET=$(./tools/target-triple.exe)" >> $GITHUB_ENV
          echo "VERSION=$(python ./tools/evalver.py --version)" >> $GITHUB_ENV

      - name: Build orbit binary
        run: cargo build --release

      - name: Test
        run: cargo test

      - name: Build installer binary
        run: cargo build --bin install --release

      - name: Package and compress binary executable
        run: python ./tools/pack.py ${{ env.VERSION }}-${{ env.TARGET }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PROJECT }}-${{ env.VERSION }}-${{ env.TARGET }}
          path: ./${{ env.PROJECT }}-${{ env.VERSION }}-${{ env.TARGET }}.zip