name: check-release
on:
  workflow_call:
    outputs:
      ready:
        description: 'Auto-release conditional indicator'
        value: ${{ jobs.parameters.outputs.ready }}

jobs:
  check-release:
    runs-on: ubuntu-latest
    outputs:
      ready: ${{ steps.ready.outputs.ready }}
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.x
          
      - name: Evaluate Cargo crate version
        id: ready
        run: echo "::set-output name=ready::$(python ./tools/evalver.py)"
