name: check-release
on:
  workflow_call:
    outputs:
      ready:
        description: 'Auto-release conditional indicator'
        value: ${{ jobs.parameters.outputs.ready }}

jobs:
  check-release:
    runs-on: ubuntu-latest
    outputs:
      ready: ${{ steps.ready.outputs.ready }}
    steps:
      - uses: actions/checkout@v2
      - name: Evaluate Cargo crate version
        id: ready
        run: echo "::set-output name=ready::0"
