name: check-release
on:
  workflow_call:
    outputs:
      ready:
        description: 'Auto-release conditional indicator'
        value: ${{ jobs.parameters.outputs.ready }}
      version:
        description: 'Version to release'
        value: ${{ jobs.parameters.outputs.version }}

jobs:
  check-release:
    runs-on: ubuntu-latest
    outputs:
      ready: ${{ steps.ready.outputs.ready }}
      version: ${{ steps.ready.outputs.version }}
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v2

      - name: Grab git tags
        run: git fetch --prune --unshallow --tags
        
      - name: Setup python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.x

      - name: Extract Cargo crate version
        id: version
        run: echo "::set-output name=version::$(./tools/evalver.py --version)"

      - name: Evaluate Cargo crate version
        id: ready
        run: echo "::set-output name=ready::$(./tools/evalver.py)"