name: docker
on:
  workflow_call:
    inputs:
      version:
        description: 'Version released'
        required: true
        type: string
    secrets:
      DOCKER_HUB_USERNAME:
        required: true
      DOCKER_HUB_ACCESS_TOKEN:
        required: true

jobs:
  build-orbit-latest-ubuntu-2204:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Download package
        uses: actions/download-artifact@v3
        with:
          name: orbit-${{ inputs.version }}-x86_64-linux

      - name: Download checksums
        uses: actions/download-artifact@v3
        with:
          name: orbit-${{ inputs.version }}-checksums

      - name: Verify contents
        run: grep $(sha256sum orbit-${{ inputs.version }}-x86_64-linux.zip) orbit-${{ inputs.version }}-checksums.txt

      - name: Install Orbit
        run: |
          unzip ./orbit-${{ inputs.version }}-x86_64-linux.zip
          cp ./orbit-${{ inputs.version }}-x86_64-linux/bin/orbit ./orbit

      - name: Test Orbit
        run: ./orbit --version

      - name: Modify entrypoint file permission to executable
        run: chmod +x ./docker/ubuntu22/entrypoint.sh
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/ubuntu22/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/orbit:latest-ubuntu-22.04
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/orbit:latest-ubuntu-22.04
          cache-to: type=inline

  build-orbit-latest-ubuntu-1804:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Modify entrypoint file permission to executable
        run: chmod +x ./docker/ubuntu18/entrypoint.sh
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/ubuntu18/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/orbit:latest-ubuntu-18.04
          build-args: REV=${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/orbit:latest-ubuntu-18.04
          cache-to: type=inline

  build-fpga-simulation-ghdl:
    needs: [build-orbit-latest-ubuntu-2204]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/fpga/ghdl/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fpga-simulation-ghdl:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/fpga-simulation-ghdl:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/fpga-simulation-ghdl:buildcache,mode=max

  build-fpga-toolchain:
    needs: [build-orbit-latest-ubuntu-1804]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/fpga/quartus/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fpga-toolchain:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/fpga-toolchain:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/fpga-toolchain:buildcache,mode=max

  build-fpga-simulation-msim:
    needs: [build-orbit-latest-ubuntu-1804]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/fpga/modelsim/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fpga-simulation-msim:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/fpga-simulation-msim:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/fpga-simulation-msim:buildcache,mode=max