name: github pages
on:
  push:
    branches:
      - trunk

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install python packages
        run: |
          pip install toml

      - name: Setup mdbook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.31'
          # mdbook-version: 'latest'

      - name: Update manual pages
        run: python ./tools/mansync/mangen.py
        
      - name: Insert current version into docs
        run: python ./tools/sync_docs_version.py ./docs/src/starting/installing.md

      - name: Generate book
        run: mdbook build ./docs/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/trunk' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/book/
          commit_message: ${{ github.event.head_commit.message }}
