name: integrity
on: 
  workflow_call:

jobs:
  integrity:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch Repository
      uses: actions/checkout@v2

    - name: Setup python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.x

    - name: Download artifacts
      uses: actions/download-artifact@v2

    - name: Display filesystem contents
      run: ls -R

    - name: Compute checksums
      run: echo "$(./tools/sum.py "./**/orbit-*.zip")" > ./checksum.txt

    - name: Review checksums
      run: cat ./checksum.txt

    - name: Upload checksums
      uses: actions/upload-artifact@v2
      with:
        name: checksum
        path: ./checksum.txt