name: integrity
on: 
  workflow_call:

jobs:
  integrity:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch Repository
      uses: actions/checkout@v2

    - name: Setup python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.x

    - name: Download artifacts
      uses: actions/download-artifact@v2

    - name: Display filesystem contents
      run: ls -R

    - name: Identify current version
      run: echo "VERSION=$(./tools/evalver.py --version)" >> $GITHUB_ENV

    - name: Compute checksums
      run: echo "$(./tools/sum.py "./**/orbit-*.zip")" > ./orbit-${{ env.VERSION }}-checksums.txt

    - name: Review checksums
      run: cat ./orbit-${{ env.VERSION }}-checksums.txt

    - name: Upload checksums
      uses: actions/upload-artifact@v2
      with:
        name: orbit-${{ env.VERSION }}-checksums
        path: ./orbit-${{ env.VERSION }}-checksums.txt