name: integrity
on: 
  workflow_call:

jobs:
  integrity:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch Repository
      uses: actions/checkout@v3

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Download artifacts
      uses: actions/download-artifact@v3

    - name: Display filesystem contents
      run: ls -R

    - name: Identify current version
      run: echo "version=$(./tools/evalver.py --version)" >> $GITHUB_ENV

    - name: Compute checksums
      run: echo "$(./tools/sum.py "./**/orbit-*.zip")" > ./orbit-${{ env.version }}-checksums.txt

    - name: Review checksums
      run: cat ./orbit-${{ env.version }}-checksums.txt

    - name: Upload checksums
      uses: actions/upload-artifact@v3
      with:
        name: orbit-${{ env.version }}-checksums
        path: ./orbit-${{ env.version }}-checksums.txt