name: integrity
on: 
  workflow_call:

jobs:
  integrity:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch Repository
      uses: actions/download-artifact@v2

    - name: Display filesystem contents
      run: ls -R

    - name: Compute checksums
      run: |
        cd ./orbit-linux-x64; sha256sum orbit-linux-x64.tar.gz >> ./../checksum.txt; cd ..
        cd ./orbit-macos-x64; sha256sum orbit-macos-x64.tar.gz >> ./../checksum.txt; cd ..
        cd ./orbit-windows-x64; sha256sum orbit-windows-x64.zip >> ./../checksum.txt; cd ..

    - name: Review checksums
      run: cat ./checksum.txt

    - name: Upload checksums
      uses: actions/upload-artifact@v2
      with:
        name: checksum
        path: ./checksum.txt