name: pipeline
on:
  push:
  workflow_dispatch:

jobs:
  build:
    uses: c-rus/orbit/.github/workflows/build.yml@trunk

  tools:
    uses: c-rus/orbit/.github/workflows/tools.yml@trunk
    
  integrity:
    uses: c-rus/orbit/.github/workflows/integrity.yml@trunk
    needs: [tools, build]

  check-release:
    uses: c-rus/orbit/.github/workflows/check-release.yml@trunk
    needs: [tools]

  release:
    uses: c-rus/orbit/.github/workflows/release.yml@trunk
    if: ${{ needs.check-release.outputs.ready == '1' }}
    needs: [check-release, integrity]
    with:
      target: ${{ needs.check-release.outputs.version }}