name: system-test
on:
  workflow_call:
    inputs:
      version:
        description: 'Version released'
        required: true
        type: string

jobs:
  linux-test:
    runs-on: ubuntu-latest
    steps:
    - name: Download package
      uses: actions/download-artifact@v3
      with:
        name: orbit-${{ inputs.version }}-x86_64-linux

    - name: Download checksums
      uses: actions/download-artifact@v3
      with:
        name: orbit-${{ inputs.version }}-checksums

    - name: Verify contents
      run: grep $(sha256sum orbit-${{ inputs.version }}-x86_64-linux.zip) orbit-${{ inputs.version }}-checksums.txt

    - name: Install Orbit
      run: |
        unzip ./orbit-${{ inputs.version }}-x86_64-linux.zip
        echo "y\n" | ./orbit-${{ inputs.version }}-x86_64-linux/install

    - name: Test Orbit
      run: orbit --version
    
  windows-test:
    runs-on: windows-latest
    steps:
    - name: Download package
      uses: actions/download-artifact@v3
      with:
        name: orbit-${{ inputs.version }}-x86_64-windows

    - name: Install Orbit
      shell: bash
      run: |
        unzip ./orbit-${{ inputs.version }}-x86_64-windows.zip
        echo "y\n" | ./orbit-${{ inputs.version }}-x86_64-windows/install.exe 

    # - name: Test Orbit
    #   run: orbit --version
